### ISSUE TITLE
Code Review for Aakash @Aak242

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2324S2-CS2113-W13-2/tp#104]
Hi! This is the code review for @Aak242. Overall good job but some coding quality/standards to follow!

**1. TaskManager.java**
1.1 Perhaps can refactor the updateTask function as method is quite long (lines 106-206)
1.2 Plural form should be used on names representing a collection of objects

Line 179
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/214dd94e-6c40-403f-b8fe-8a4aad6b1325)

Line 266-268, 273, 278. Good effort on lines 282-283
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/88b0448d-f5d8-4c34-a8a5-5d9e97d3cb73)

Line 373-375
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/56f0cd2c-176d-4658-9b71-417fc5913855)

**2. Deadline.java**
2.1 Just a minor issue with Javadoc. D and "D".
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/e9736ce7-0bd7-420d-ad82-287a3dffd4d2)

**Comment by clarencepohh** [comment]
1.1 To be resolved in future issue for v2.1
1.2 Partially complete:
 - Line 179 (now line 187), resolved in #119.
 - Lines 266-268 (now lines 314-316), incomplete. @Aak242 please do take note!
 - Lines 373-375 (now lines 545-547) resolved in #119.
 
 2.1 Resolved in #119.
 
 Please close the issue once problems are rectified.
