### ISSUE TITLE
Code Review for Clarence @clarencepohh

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2324S2-CS2113-W13-2/tp#105]
Hi! This is the code review for @clarencepohh. Overall good job but some coding quality/standards to follow!

**1. TaskManager.java**
1.1 Similar to Aakash, can consider to refactor the updateTask function as method is quite long. (lines 106-206)
1.2 Plural form should be used on names representing a collection of objects
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/3e892d67-fc1d-485a-8c8c-fa768cd1c093)

**2. Task.java**
2.1 Very minor javadoc comment. "?" vs ?.
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/ae6bf494-be58-4575-a226-de7dbaa2755c)

**3. Event.java**
3.1 Very minor javadoc comment. "E" vs E.
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/6727c8d0-914f-420f-8dca-22ab547c89a0)

**4. Main.java**
4.1 Remember to remove the unused comments after you are done with your product
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/9c5d5f91-e48c-49b5-8676-3ef274fe18eb)
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/3aadffdf-86f2-4957-a7e1-71e32407065d)

4.2 Can consider to refactor main() method too as it is quite long.

**5. Storage.java**
5.1 Very minor javadoc issue. "Punctuation behind each parameter description"
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/90f5d869-ffca-4887-bc4c-664bf180abc5)

5.2 Remember to remove the unused comments after you are done with your product
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/16e35449-1e43-4c57-be6b-94760c5529f7)

**Comment by clarencepohh** [comment]
1.1 Refactoring will be done soon, @Aak242 and @Mahesh1772 assigned
1.2 Resolved in previous PR. Will tag relevant PRs before closing.

2, 3 Resolved in previous PR.

4.1 Removed / uncommented the lines. ICS handler is still awaiting @kyhjonathan PR
4.2 See pt 1.1

5.1 Resolved in previous PR.
5.2 Removed line.
