### ISSUE TITLE
Code Review for Jonathan @kyhjonathan

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2324S2-CS2113-W13-2/tp#106]
Hi! This is the code review for @kyhjonathan. Overall good job but some coding quality/standards to follow!

**1. Storage.java**
1.1 Very minor javadoc issue. "Punctuation behind each parameter description"
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/74f45473-780a-4c44-853d-d8312dde601d)

1.2 Remember to remove uncommented codes
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/0fe2aafa-226a-4449-a2fc-3f36dbc73153)

**2. Main.java**
2.1 Similar to Clarence's comment, try to refactor main method as it is quite long!
2.2 Remember to remove uncommented codes when you submit your product.
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/2e582284-bcd3-4a64-8f10-f5b15e04e444)

**3. DateUtils.java**
3.1 Avoid magic numbers (understand that this is the days of the week) - could be placed as named constants
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/c8327d7f-5f3c-41f3-a700-07296acc7a12)

**Comment by clarencepohh** [comment]
1.1, 1.2 Resolved in previous PR #119 

2.1 To be resolved in future issue for v2.1
2.2 Avatar codes have been added in, ICS awaiting implementation

3.1 Resolved in previous PR #119
