### ISSUE TITLE
Code Review for Nicholas @NicholasTanYY

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2324S2-CS2113-W13-2/tp#107]
Hi! This is the code review for @NicholasTanYY. Overall good job (great refactoring of UiRenderer.java) but some coding quality/standards to follow!

1. Main.java
1.1 Similar to other reviews, do refactor the main() method as it is quite long!
1.2 Remember to uncomment out unused code when you submit your product
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/24c2d1e0-38a0-4d63-9edb-a7f28a8689d1)

**Comment by clarencepohh** [comment]
1.1 To be resolved in future issue for v2.1
1.2 Uncommented in previous PR #110. ICS handler awaiting implementation.
