### ISSUE TITLE
Code Review for Mahesh @Mahesh1772

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2324S2-CS2113-W13-2/tp#108]
Hi! This is the code review for @Mahesh1772. Overall good job but some coding quality/standards to follow!

**1. Do remember to include in some javadocs for your methods**
**2. MonthView.java**
2.1 Avoid magic numbers - could use a named constant
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/930040bd-a30a-4f06-a945-c92eccd7d6d6)
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/78edaa9e-00a7-42c1-bc0b-47dc954d5611)

**3. Main.java**
3.1 Remember to remove uncommented codes out when you submit your product
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/69451253/945ba3ae-4d65-4489-b9e7-e6de02f023b9)
3.2 Similar to other reviews, do refactor main method!

**Comment by clarencepohh** [comment]
1. To resolve in a future issue for v2.1

2.1 Resolved in previous PR #103 
3.1 Removed in previous PR.
