### ISSUE TITLE
unable to run clinton.jar 

### ISSUE THREAD

**Issue by jthibault03** [AY2324S2-CS2113-W13-2/tp#122]
![image](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/98941496/687a893f-7e94-4ba8-8280-74cfe11ada23)

**Comment by clarencepohh** [comment]
Thanks for notifying us about this issue. We will work on resolving it!

**Comment by clarencepohh** [comment]
Closed as jar file was updated with new release. To take note for future releases
