### ISSUE TITLE
[PE-D][Tester B] Unhandled exception for entering only 1 info for Event start date and time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W13-2/tp#128]
## Description
Providing only 1 input will result in the array index out of bound as there isn't 2 elements to retrieve

## Screenshot
![image.png](https://raw.githubusercontent.com/wenenhoe/ped/main/files/09a61524-36e9-40e8-8b48-a1d16659780e.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wenenhoe/ped#3

**Comment by clarencepohh** [comment]
Closing issue as fixed in #147
