### ISSUE TITLE
Bug: task added to wrong date when in month view

### ISSUE THREAD

**Issue by NicholasTanYY** [AY2324S2-CS2113-W13-2/tp#154]
![Screenshot from 2024-04-13 20-19-52](https://github.com/AY2324S2-CS2113-W13-2/tp/assets/77789163/22f0b6dc-b0a9-4664-9ca7-66becee995f0)

As seen in the image, the todo is added to 4 apr instead of 3 apr.

**Comment by clarencepohh** [comment]
Issue seems to be within findDateFromDayNumber; it is handled in the else branch (when in weekView) but not handled when in monthView

**Comment by clarencepohh** [comment]
Fixed in #155
